config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get('/', to: 'ideas#index', as: :root)
  resources :ideas, except: [:index] do
    resources :reviews, only: [:create, :destroy], shallow: true
  end

  resources :users, only: [:new, :create]

  resource :session, only: [:new, :create, :destroy]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, Idea do |idea|
      idea.user == user
    end

    user ||= User.new

    if user.is_admin
      can :manage, :all
    end

    can :manage, Review do |review|
      review.user == user
    end

  end
end
    # Define abilities for the passed in user here. For example:
    #
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy

  validates :title, :description, presence: true

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :idea
  belongs_to :user

  validates :comment, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ideas, dependent: :nullify
  has_many :reviews, dependent: :nullify

  validates :first_name, :last_name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user = User.find_by(id: session[:user_id]) if session[:user_id].present?
  end

  helper_method :current_user

  def authenticate_user!
    unless current_user.present?
      flash[:alert] = 'Please sign in or sign up first'
      redirect_to new_session_path
    end
  end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  before_action :find_idea, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]
  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new idea_params
    @idea.user = current_user
    if @idea.save
      redirect_to root_path
    else
      flash.now[:alert] = @idea.errors.full_messages.join(', ')
      render :new
    end
  end

  def index
    @ideas = Idea.order(created_at: :desc)
  end

  def show
    @review = Review.new
    @reviews = @idea.reviews.order(created_at: :desc)
  end

  def edit
  end

  def update
    if @idea.update idea_params
      redirect_to idea_path(@idea)
    else
      flash.now[:alert] = @idea.errors.full_messages.join(', ')
      render :edit
    end
  end

  def destroy
    @idea.destroy
    redirect_to root_path
  end

    @idea

  private

  def find_idea
    @idea = Idea.find params[:id]
  end

  def idea_params
    params.require(:idea).permit(:title, :description)
  end

  def authorize_user!
    unless can?(:manage, @idea)
      flash[:alert] = "Access Denied"
      redirect_to root_path
    end
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  before_action :find_review, only: [:destroy]
  before_action :authorize_user!, only: [:destroy]

  def create
    @review = Review.new review_params
    @review.idea = Idea.find params[:idea_id]
    @review.user = current_user

    if @review.save
      redirect_to idea_path(@review.idea)
    else
      flash.now[:alert] = @review.errors.full_messages.join(', ')
      @idea = @review.idea
      @reviews = @idea.reviews.order(created_at: :desc)
      render "ideas/show"
    end
  end

  def destroy
    @review.destroy
    redirect_to idea_path(@review.idea)
  end

  private

  def find_review
    @review = Review.find params[:id]
  end

  def review_params
    params.require(:review).permit(:comment)
  end

  def authorize_user!
    unless can?(:manage, @review)
      flash[:alert] = "Access Denied"
      redirect_to root_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if @user = User.find_by(email: params[:session][:email])
      session[:user_id] = @user.id
      flash[:notice] = "Welcome, #{@user.first_name}"
      redirect_to root_path
    else
      flash[:alert] = "Email not found"
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      flash[:notice] = "Welcome, #{@user.first_name}"
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash.now[:alert] = @user.errors.full_messages.join(', ')
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/edit.html.erb
<%= form_for @idea do |f| %>
  <%= f.label :title %> <br>
  <%= f.text_field :title %> <br>
  <%= f.label :description %> <br>
  <%= f.text_area :description %> <br>
  <%= f.submit "Update", class: "btn btn-dark"  %>
<% end %>

app/views/ideas/index.html.erb
<% @ideas.each do |idea| %>
  <div class="idea-container">
    <h3>
      <small class="description-toggle">➕</small>
      <%= link_to idea.title, idea_path(idea) %> <small>by <%= idea.user.first_name %> </small>
    </h3>
    <p class="idea-description hidden"><%= idea.description %></p>
    <small><%= idea.created_at.to_date.to_formatted_s(:rfc822) %></small>
    <hr>
  </div>
<% end %>

app/views/ideas/new.html.erb
<%= form_for @idea do |f| %>
  <%= f.label :title %> <br>
  <%= f.text_field :title, placeholder: "Idea Title.." %> <br>
  <%= f.label :description %> <br>
  <%= f.text_area :description, placeholder: "What's your idea.." %> <br>
  <%= f.submit "Post", class: "btn btn-dark"  %>
<% end %>

app/views/ideas/show.html.erb
<h1> <%= @idea.title %> </h1>
<p> <%= @idea.description %> </p>

<small>
  By <%= @idea.user.first_name %> <%= time_ago_in_words(@idea.created_at) %> ago.
</small>
<% if can?(:manage, @idea) %>
  <%= link_to 'edit', edit_idea_path(@idea) %>
  <%= link_to 'delete', idea_path(@idea), method: :delete %>
<% end %>

<div class="container-fluid" id="new-review-form">
  <%= form_for [@idea, @review] do |f| %>
    <%= f.text_area :comment, placeholder: "Would you like to share your thoughts?" %> <br>
    <%= f.submit 'Add Review', class: "btn btn-dark" %>
  <% end %>
</div>

<% @reviews.each do |review| %>
  <div class="review-container">
    <p><%= review.comment %></p>
    <small>By <%= review.user.first_name %> <%= time_ago_in_words(@idea.created_at) %> ago.</small>
    <% if can?(:manage, review) %>
      <%= link_to 'delete', review_path(review), method: :delete %>
    <% end %>
    <hr>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaFactory</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav>
      <div class="container-fluid">
        <%= link_to '💡', root_path, id:"nav-logo"%>
        <% if current_user.present? %>

          <button type="button" class="btn btn-dark" data-toggle="modal" data-target="#newIdeaForm">
            New Idea
          </button>

          <span><strong><%= current_user.first_name %></strong></span>
          <!-- <%= link_to 'New Idea', new_idea_path %> -->
          <%= link_to 'Sign Out', session_path, method: :delete %>
        <% else %>
          <%= link_to 'Sign In', new_session_path %>
          <%= link_to 'Sign Up', new_user_path %>
        <% end %>
      </div>
      <hr>
    </nav>

    <% if flash[:notice] %>
      <div class="alert alert-success" role="alert">
        <p><%= flash[:notice] %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-warning" role="alert">
        <p><%= flash[:alert] %></p>
      </div>
    <% end %>

    <div class="container-fluid">
      <%= yield %>
    </div>

    <div class="modal" id="newIdeaForm" tabindex="-1">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="modalLabel">New Idea Form</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form class="new_idea" method="post" action="/ideas">
              <input name="utf8" type="hidden" value="✓">
              <input type="hidden" name="authenticity_token" value="Lvw+fHeHOMgPy57+9G8D+Ag+8f+x7zAfiADk6tkSAFglqPHoA9goUI9kgHtgkcWH67LuGQfMjR8zWqx0zJhxaA==">
              <label for="idea_title">Title</label>
              <br>
              <input placeholder="Idea Title.." type="text" name="idea[title]" id="idea_title">
              <br>
              <label for="idea_description">Description</label>
              <br>
              <textarea placeholder="What's your idea.." name="idea[description]" id="idea_description"></textarea>
              <div class="modal-footer">
                <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Close</button>
                <input type="submit" name="commit" value="Post" class="btn btn-dark" data-disable-with="Post">
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>

    <script>
      document.querySelectorAll('.description-toggle').forEach(node => {
        node.addEventListener('click', event => {
          const {currentTarget} = event
          targetDescription = currentTarget.parentElement.parentElement.querySelector('.idea-description')
          if (currentTarget.innerHTML === '➕') {
            currentTarget.innerHTML = '➖'
            targetDescription.classList.remove('hidden')
          } else {
            currentTarget.innerHTML = '➕'
            targetDescription.classList.add('hidden')
          }
        });
      });
    </script>

  </body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :first_name %> <br>
  <%= f.text_field :first_name %> <br>
  <%= f.label :last_name %> <br>
  <%= f.text_field :last_name %> <br>
  <%= f.label :email %> <br>
  <%= f.text_field :email %> <br>
  <%= f.submit "Sign Up", class: "btn btn-dark" %>
<% end %>